language: generic
os: linux

script:
    - curl -SsL https://easylist-downloads.adblockplus.org/advblock.txt | grep -P '^(\|\|)((?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9])(\^|\^\$popup|\^\$third-party)?$' | tr -d '|' | sed 's/\^\$popup//' | sed 's/\^\$third-party//' | tr -d '^' > blocklist-ru.txt

before_deploy:
    - git config --local user.name "aleksey-suprun"
    - git config --local user.email "aleksey.suprun@gmail.com"
    - git tag -f release

deploy:
  provider: releases
  api_key:
    secure: c9O/kPbYCj0pEmWgTfMFekL1ueEGPzJIN2+1VmaI/V+mzV/ZdtW/Do8oWBliuE/BBeXTDtHoVt+m0xCXha0UecI42BnHJmmjPZ1z+1K2VqDBu3/bRvrNuf4h1+mKZrLfQwp3wqVGOOXkRTPAtAzRYWd4aQraAtP9WmbklKUVQeUjy/iWfTJokV50yOiKD5GtwDKdRj2/9D4cSuSDo52YCjCZbfNS5lG4dJuKk8DNbcURh1drvyPaWydStvoW2bAzn/wDq44skj3FUR1HOPpqtGUauR8w2bXPgCSmhFCm/LjOegTmEPlb1mzJXm9URlMkTzcOxGazt9dVT4O/N6kWi7IjL2Eosa7m35ustXs8/mcRWjZ7lyuI5tKbFSvrUK5N+wLTMojvTfOEa4X7H27ZRtd2VWmJiKof2AQgJMs3kxxyJZzXau5YgecnuLwCT5C8ZLkva4D/gh3p4kV9zUGoJ5IG8zWcJHWcMbt/Fz/3FxEfRsgg3E7ivJzLiY1RDGw6jIvlzBVir8X9nguiVu5Zf8dHGiRKONB2vdd03kB2VCoOO4TNZhI4SzuPtq2EOVtEwjV7jARsibDjctJQISRspSj3jrzFjdtlz55Wrf1cNurJsAi16NjsPoDzUvP4WP4O/KhrZpHuPhq5ZBcaT5x6YCaOzTkDGPKYsz975gO7bMY=
  file: blocklist-ru.txt
  skip_cleanup: true
  overwrite: true
  on:
    repo: aleksey-suprun/pi-hole-blocklist
    branch: master

notifications:
  slack:
    secure: g7Y2DKDVVlHNi7jouXWc898M4LklBjYakLgA7cgPZC5QSHX2kt3iWUrVfNJBdiKXbBzHYTqIEc4kROFQQzacIbCbVAvXkXd76dgCOq0Ngnz6Fd4AxyQLyvg6+18QFXF0aaBui1LkRny6z08uEZuQpmfwZAKL/axhJOp3iqxYd1L5FGuBlXf32ixzlKV9lhcmWUYJ8tiWXj1NCwomQ2RePTvjnzVz+0EueB0MBkveG77byDY07pIJpZ5xEKDulN3oUmHAGH6XfuPu9J+jTI1783ewZllKbNd1AGGXoK03Xsx2f4w2D2vG6LfOgCnXAOOJSOBnUyg85WlgwZqc8z25fypoZQWIezapzIlzW1U8ZGscvjnROoTpeFGnrpOFqGMCt3MJCjbBEEjGOmpKxn5PGZuHR1qJvNtRaAA6wKU85ZjWPWOnuiKV76c0C1QPTkqhwybrTGw8tzqlMrvn6JqC5url7cGPUsK8vFoI4maFeEKcz6l9pxMMIYSmygJz44xlikwUdg+RS6ZnCjrzH51+JLoyRxm2u437nP5GXdOuyc+/uHmY+8Auuz0Yq06FcjBi2O0egtwa31cCvFLxBudpQlXkhhBZioWildk6834kgZttrI5na81mi5A73cKZ8zumYwHqzYnE4ZFMQP7vIiS8yPgs7wSkWS8rXx9zigjOZNE=